name: educa_project

services:

  db:
    image: postgres:17
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  backend:
    build: .
    # Build image from Dockerfile in the current directory (.)

    command: ["./wait-for-it.sh", "db:5432", "--",
              "uwsgi", "--ini", "/app/config/uwsgi/uwsgi.ini"]
      # Override CMD from Dockerfile
      # the script ./wait-for-it.sh waits for db to be ready, separated by -- once ready, run the remaining script.
      # It polls db:5432 until it accepts connections, then runs everything after --.

    restart: always
    # This defines the restart policy for the container. Using always, the container
    # is always restarted if it stops. This is useful for production environments.

    volumes:
      - .:/app
    # Mount the current directory-> /app in container
    # Changes on your computer instantly appear in container!
    # Format: local_path:container_path

# Not required as uWSGI will be reachable with a socket, so don't need to expose port in the container.
#    ports:
#      - "8000:8000"
    # Map ports: your_computer:container
    # localhost:8000 on your PC -> port 8000 in container

    env_file:
      - .env  # Loads variables from .env files
    # Set environment variables inside the container

    depends_on:
#      - memcached
      - db
      - redis

    environment:
      - DJANGO_SETTINGS_MODULE=educa.settings.prod
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  redis:
    image: redis:7-alpine
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"


  nginx:
    image: nginx:1.30.5
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/app
    ports:
      - "80:80"


  # another service for cache
#  memcached:
#    image: memcached:1.6-alpine
#
#    container_name: educa_memcached
#
#    ports:
#      - "11211:11211"


volumes:
  postgres_data:
  redis_data:
