# Generated by Django 5.2.17 on 2026-09-14 12:49

import django_nh3.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=django_nh3.models.Nh3Field(),
        ),
    ]
