[uwsgi]
; Create a Unix socket file at this path. Nginx will point
; to this exact file to talk to uWSGI. This replaces a port.
socket=/app/uwsgi_app.sock
chdir = /app/
module=educa.wsgi:application
master=true

; Set file permission on the socket file so Nginx can read/write it.
; 666= readable and writable by everyone (owner, group, others).
chmod-socket=666
uid=www-data
gid=www-data
vacuum=true